# This file was generated by GoReleaser. DO NOT EDIT.
cask "orla" do
  version "1.2.15"

  on_macos do
    on_intel do
      sha256 "e2dbdc05dc626d58a8b3e8c4d44235f5525557015541870650049a6efa95e624"
      url "https://github.com/harvard-cns/orla/releases/download/v#{version}/orla-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "470af319a1f80eda9d775baa9ff118b061d2a59ac746c800c4a4ccba3dc53b43"
      url "https://github.com/harvard-cns/orla/releases/download/v#{version}/orla-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "210d7f177a9393b9e2a48b21c8d5f9d9e0c5dc168c854aee4192fec2ffd2f877"
      url "https://github.com/harvard-cns/orla/releases/download/v#{version}/orla-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "717ec7af19ac8dbc4362fb2136194982cbe8ad1c50ed41b6ae65d8806e2fe759"
      url "https://github.com/harvard-cns/orla/releases/download/v#{version}/orla-linux-arm64.tar.gz"
    end
  end

  name "orla"
  desc "A dead-simple unix tool for lightweight agents"
  homepage "https://github.com/harvard-cns/orla"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orla"

  postflight do
    skip_ollama = ENV["HOMEBREW_ORLA_SKIP_OLLAMA"] == "1"
    if skip_ollama
      system "/bin/sh", "-c", "export PATH=\"/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:$PATH\" && curl -fsSL https://raw.githubusercontent.com/harvard-cns/orla/main/scripts/install.sh | sh -s -- --homebrew --skip-ollama"
    else
      system "/bin/sh", "-c", "export PATH=\"/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:$PATH\" && curl -fsSL https://raw.githubusercontent.com/harvard-cns/orla/main/scripts/install.sh | sh -s -- --homebrew"
    end
  end

  # No zap stanza required

end
